spack:
  specs:
    - crystfel
    - py-calibration-services
    - py-cfelpyutils
    - py-extra-data
    - py-extra-geom
    - py-karabo-bridge
    - py-msgpack-numpy
    # - py-pyfai
    - py-pyopengl
  view: False
  concretization: together
