name: {PACKAGE}

on:
  push:
    branches: [ master ]
    paths: ['packages/{PACKAGE}/**']
  pull_request:
    branches: [ master ]
    paths: ['packages/{PACKAGE}/**']

jobs:
  package-test-{PACKAGE}:
    runs-on: ubuntu-latest
    container:
      image: robertrosca/panosc-spack-centos7@sha256:2485bf065ffd5cccff8f3acc98476ff0add22ef11a47516630deec949720265e
    steps:
      - uses: actions/checkout@v2
      - run: |
          source /opt/spack/share/spack/setup-env.sh
          echo Spack version: $(spack --version)
          echo Tests for package {PACKAGE}
          spack repo add --scope=site ./
          spack-parallel spack install --test=root --verbose {PACKAGE}
