name: {PACKAGE}

on:
  push:
    branches: [ master ]
    paths: ['packages/{PACKAGE}/**']
  pull_request:
    branches: [ master ]
    paths: ['packages/{PACKAGE}/**']

jobs:
  package-test-{PACKAGE}:
    runs-on: ubuntu-latest
    container:
      image: robertrosca/panosc-spack-centos7:0.16.0v3
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo Spack version: $(spack --version)
          echo Tests for package {PACKAGE}
          spack repo add --scope=site ./
          spack install --test=root --verbose {PACKAGE}
