name: py-msgpack-numpy

on:
  push:
    branches: [ master ]
    paths: ['packages/py-msgpack-numpy/**']
  pull_request:
    branches: [ master ]
    paths: ['packages/py-msgpack-numpy/**']

jobs:
  package-test-py-msgpack-numpy:
    runs-on: ubuntu-latest
    container:
      image: robertrosca/panosc-spack-centos7@sha256:ead0fa85360070a21a29e1e3c3879181f42683b8a1fc43a55bdd6cb3edf86d68
    steps:
      - uses: actions/checkout@v2
      - run: |
          source /opt/spack/share/spack/setup-env.sh
          echo Spack version: $(spack --version)
          echo Tests for package py-msgpack-numpy
          spack repo add --scope=site ./
          spack-parallel spack install --test=root --verbose py-msgpack-numpy
