name: py-extra-data

on:
  push:
    branches: [ master ]
    paths: ['packages/py-extra-data/**']
  pull_request:
    branches: [ master ]
    paths: ['packages/py-extra-data/**']

jobs:
  package-test-py-extra-data:
    runs-on: ubuntu-latest
    container:
      image: robertrosca/panosc-spack-centos7:0.16.0v2
    steps:
      - uses: actions/checkout@v2
      - run: |
          source /opt/spack/share/spack/setup-env.sh
          echo Spack version: $(spack --version)
          echo Tests for package py-extra-data
          spack repo add --scope=site ./
          spack install --test=root --verbose py-extra-data
