name: py-cfelpyutils

on:
  push:
    branches: [ master ]
    paths: ['packages/py-cfelpyutils/**']
  pull_request:
    branches: [ master ]
    paths: ['packages/py-cfelpyutils/**']

jobs:
  package-test-py-cfelpyutils:
    runs-on: ubuntu-latest
    container:
      image: robertrosca/panosc-spack-centos7:0.16.0v3
    steps:
      - uses: actions/checkout@v2
      - run: |
          source /opt/spack/share/spack/setup-env.sh
          echo Spack version: $(spack --version)
          echo Tests for package py-cfelpyutils
          spack repo add --scope=site ./
          spack install --test=root --verbose py-cfelpyutils
