name: py-karabo-bridge

on:
  push:
    branches: [ master ]
    paths: ['packages/py-karabo-bridge/**']
  pull_request:
    branches: [ master ]
    paths: ['packages/py-karabo-bridge/**']

jobs:
  package-test-py-karabo-bridge:
    runs-on: ubuntu-latest
    container:
      image: robertrosca/panosc-spack-centos7:0.16.0v1
    steps:
      - uses: actions/checkout@v2
      - run: |
          source /opt/spack/share/spack/setup-env.sh
          echo Spack version: $(spack --version)
          echo Tests for package py-karabo-bridge
          spack repo add --scope=site ./
          spack install --test=root --verbose py-karabo-bridge
