name: SHA version update

on:
  pull_request:
    branches: ['dependabot/pip/dot-github/dependabot/*']

jobs:
  update-sha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ./.github/update-sha.sh
